name: estate_ops_tenant
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auth0_flutter: ^1.6.0
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.3
  path_provider: ^2.1.2
  flutter_flavor: ^3.1.3
  get_it: ^7.6.6
  equatable: ^2.0.5
  chopper: ^7.1.1+1
  json_annotation: ^4.8.1
  intl: any
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  form_builder_image_picker: ^4.0.0
  cross_file: ^0.3.3
  pdfx: ^2.6.0
  file_saver: ^0.2.12
  mime: ^1.0.5
  url_launcher: ^6.2.6
  firebase_core: ^2.25.5
  firebase_messaging: ^14.7.17
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  chopper_generator: ^7.1.1
  json_serializable: ^6.7.1
  swagger_dart_code_generator: ^2.10.4
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
